### PR TITLE
ExoPlayer r1.5.6 (was r1.4.2)

### PR DESCRIPTION
**Pull request by talklittle**

### CODE REVIEW

**Comment by luciofm** [comment]
Any news on this??? We can't update ExoPlayer on our App because it conflicts with MoPub old version...

**Comment by tmsoft** [comment]
ExoPlayer really needs to be updated at this point to address Android 6.0 compatibility issues.  Because MoPub is using an outdated ExoPlayer library it causes the gradle build to automatically add STORAGE permissions to our game which is now considered a dangerous permission.  This permission requires prompting the user for access and the Google Play team has told me it shouldn't be used if it is not needed.  The latest version of ExoPlayer removes the STORAGE permissions.  All that should be required is updating the dependency to the latest version of ExoPlayer or at least version 1.5.2 where this problem was fixed.  Thanks

**Comment by talklittle** [comment]
Created a topic on official MoPub forum: https://twittercommunity.com/t/mopub-android-sdk-needs-exoplayer-library-update/63710

**Comment by tmsoft** [comment]
I've reached out to my contact at MoPub so hopefully this issue will be investigated.  Have you actually tested video ads w/ the latest version to make sure it still works okay?

**Comment by MoJRen** [comment]
Our current plan is to integrate and test the latest version of ExoPlayer and release an updated version of the SDK in the near future.

**Comment by blogvinskiy** [comment]
We've shipped 4.5.1 which includes ExoPlayer 1.5.6.

**Pull request closed without merging**
